from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0ca5ca87a12f"
down_revision: str | None = "b134fcecaa46"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster_history_status", schema=None) as batch_op:
        batch_op.add_column(sa.Column("rebuilding_since", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster_history_status", schema=None) as batch_op:
        batch_op.drop_column("rebuilding_since")

    # ### end Alembic commands ###
