from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2c4e76738551"
down_revision: str | None = "61dceef48dfc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_tile", schema=None) as batch_op:
        batch_op.add_column(sa.Column("time", sa.DateTime(), nullable=True))
        batch_op.create_index(
            "idx_activity_tile_zoom_activity", ["zoom", "activity_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("activity_tile", schema=None) as batch_op:
        batch_op.drop_index("idx_activity_tile_zoom_activity")
        batch_op.drop_column("time")

    # ### end Alembic commands ###
