from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "544913320a42"
down_revision: str | None = "9f216899084a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "duplicate_candidates",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("activity_a_id", sa.Integer(), nullable=False),
        sa.Column("activity_b_id", sa.Integer(), nullable=False),
        sa.Column("detected_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["activity_a_id"],
            ["activities.id"],
        ),
        sa.ForeignKeyConstraint(
            ["activity_b_id"],
            ["activities.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("activity_a_id", "activity_b_id"),
    )
    with op.batch_alter_table("config_activity_import", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "duplicate_matching_enabled",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "duplicate_matching_auto_resolve",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "duplicate_time_tolerance_seconds",
                sa.Integer(),
                server_default="300",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "duplicate_relative_tolerance",
                sa.Float(),
                server_default="0.1",
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "duplicate_source_priorities",
                sa.JSON(),
                server_default='{"directory": 10, "strava": 20, "hammerhead": 30}',
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_activity_import", schema=None) as batch_op:
        batch_op.drop_column("duplicate_source_priorities")
        batch_op.drop_column("duplicate_relative_tolerance")
        batch_op.drop_column("duplicate_time_tolerance_seconds")
        batch_op.drop_column("duplicate_matching_auto_resolve")
        batch_op.drop_column("duplicate_matching_enabled")

    op.drop_table("duplicate_candidates")
    # ### end Alembic commands ###
