from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "5a0b3ee0e9da"
down_revision: str | None = "920d66e81d53"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster_tile_activations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("zoom", sa.Integer(), nullable=False),
        sa.Column("tile_x", sa.Integer(), nullable=False),
        sa.Column("tile_y", sa.Integer(), nullable=False),
        sa.Column("event_index", sa.Integer(), nullable=False),
        sa.Column("activity_id", sa.Integer(), nullable=False),
        sa.Column("time", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["activity_id"],
            ["activities.id"],
            name="cluster_tile_activation_activity_id",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "zoom", "tile_x", "tile_y", name="uq_cluster_tile_activation_per_zoom"
        ),
    )
    with op.batch_alter_table("cluster_tile_activations", schema=None) as batch_op:
        batch_op.create_index(
            "idx_cluster_tile_activations_zoom_activity",
            ["zoom", "activity_id"],
            unique=False,
        )
        batch_op.create_index(
            "idx_cluster_tile_activations_zoom_event",
            ["zoom", "event_index"],
            unique=False,
        )
        batch_op.create_index(
            batch_op.f("ix_cluster_tile_activations_activity_id"),
            ["activity_id"],
            unique=False,
        )

    with op.batch_alter_table("cluster_history_checkpoints", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("idx_cluster_history_checkpoints_zoom_index"))

    op.drop_table("cluster_history_checkpoints")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cluster_history_checkpoints",
        sa.Column("id", sa.INTEGER(), nullable=False),
        sa.Column("zoom", sa.INTEGER(), nullable=False),
        sa.Column("event_index", sa.INTEGER(), nullable=False),
        sa.Column("time", sa.DATETIME(), nullable=True),
        sa.Column("max_cluster_size", sa.INTEGER(), nullable=False),
        sa.Column("payload_json", sa.TEXT(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "zoom", "event_index", name=op.f("uq_cluster_history_checkpoints")
        ),
    )
    with op.batch_alter_table("cluster_history_checkpoints", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("idx_cluster_history_checkpoints_zoom_index"),
            ["zoom", "event_index"],
            unique=False,
        )

    with op.batch_alter_table("cluster_tile_activations", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_cluster_tile_activations_activity_id"))
        batch_op.drop_index("idx_cluster_tile_activations_zoom_event")
        batch_op.drop_index("idx_cluster_tile_activations_zoom_activity")

    op.drop_table("cluster_tile_activations")
    # ### end Alembic commands ###
