import json
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "61dceef48dfc"
down_revision: str | None = "69a0a6c5d1de"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "explorer_filter_json", sa.Text(), server_default="{}", nullable=False
            )
        )

    _carry_over_achievement_kinds()

    with op.batch_alter_table("kinds", schema=None) as batch_op:
        batch_op.drop_column("consider_for_achievements")


def _carry_over_achievement_kinds() -> None:
    """Turn the old per-kind flag into the explorer filter it replaces.

    Only kinds that were considered for achievements count from now on, so an
    existing installation keeps exactly the tiles it had. If every kind counted,
    the filter stays empty, which means "count everything".
    """
    connection = op.get_bind()
    kinds = connection.execute(
        sa.text("select id, consider_for_achievements from kinds")
    ).all()
    if not kinds:
        return
    counted = sorted(row[0] for row in kinds if row[1])
    if len(counted) == len(kinds):
        return
    connection.execute(
        sa.text("update config_ui set explorer_filter_json = :value"),
        {"value": json.dumps({"kind": counted}, sort_keys=True)},
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("kinds", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "consider_for_achievements",
                sa.BOOLEAN(),
                nullable=False,
                server_default=sa.true(),
            )
        )

    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.drop_column("explorer_filter_json")

    # ### end Alembic commands ###
