from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "69a0a6c5d1de"
down_revision: str | None = "2d556d529b6a"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("cluster_tile_activations", schema=None) as batch_op:
        batch_op.alter_column("activity_id", existing_type=sa.INTEGER(), nullable=True)

    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "count_inaccessible_in_cluster",
                sa.Boolean(),
                server_default=sa.text("0"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.drop_column("count_inaccessible_in_cluster")

    with op.batch_alter_table("cluster_tile_activations", schema=None) as batch_op:
        batch_op.alter_column("activity_id", existing_type=sa.INTEGER(), nullable=False)

    # ### end Alembic commands ###
