from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "920d66e81d53"
down_revision: str | None = "e55ade5bb5e3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


TRANSPARENT = "#00000000"


def _row(
    name: str,
    fill_color: str = TRANSPARENT,
    border_color: str = TRANSPARENT,
    stripe_color: str = TRANSPARENT,
) -> dict:
    return {
        "name": name,
        "fill_color": fill_color,
        "border_color": border_color,
        "border_width": 6,
        "border_stroke": "solid",
        "stripe_color": stripe_color,
    }


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    tile_styles = op.create_table(
        "tile_styles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("fill_color", sa.String(), nullable=False),
        sa.Column("border_color", sa.String(), nullable=False),
        sa.Column("border_width", sa.Integer(), nullable=False),
        sa.Column("border_stroke", sa.String(), nullable=False),
        sa.Column("stripe_color", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )

    connection = op.get_bind()
    old = (
        connection.execute(
            sa.text(
                "SELECT color_strategy_visited_color, color_strategy_max_cluster_color, "
                "color_strategy_max_cluster_other_color, color_strategy_new_tile_color, "
                "color_strategy_new_cluster_color FROM config_ui WHERE id = 1"
            )
        )
        .mappings()
        .first()
        or {}
    )

    def color(field: str, fallback: str) -> str:
        return old.get(field) or fallback

    visited = color("color_strategy_visited_color", "#0000004d")
    op.bulk_insert(
        tile_styles,
        [
            _row("visited", fill_color=visited),
            _row("missing", fill_color=visited),
            _row(
                "new_tile",
                border_color=color("color_strategy_new_tile_color", "#ff7700ff"),
            ),
            _row(
                "new_cluster",
                border_color=color("color_strategy_new_cluster_color", "#0066ffff"),
            ),
            _row(
                "max_cluster",
                fill_color=color("color_strategy_max_cluster_color", "#377eb84d"),
            ),
            _row(
                "other_cluster",
                fill_color=color("color_strategy_max_cluster_other_color", "#4daf4a4d"),
            ),
            _row("inaccessible", stripe_color="#80808099"),
        ],
    )

    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.drop_column("color_strategy_visited_color")
        batch_op.drop_column("color_strategy_max_cluster_other_color")
        batch_op.drop_column("color_strategy_new_tile_color")
        batch_op.drop_column("color_strategy_new_cluster_color")
        batch_op.drop_column("color_strategy_max_cluster_color")

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("color_strategy_max_cluster_color", sa.VARCHAR(), nullable=False)
        )
        batch_op.add_column(
            sa.Column(
                "color_strategy_new_cluster_color",
                sa.VARCHAR(),
                server_default=sa.text("'#0066ffff'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "color_strategy_new_tile_color",
                sa.VARCHAR(),
                server_default=sa.text("'#ff7700ff'"),
                nullable=False,
            )
        )
        batch_op.add_column(
            sa.Column(
                "color_strategy_max_cluster_other_color", sa.VARCHAR(), nullable=False
            )
        )
        batch_op.add_column(
            sa.Column("color_strategy_visited_color", sa.VARCHAR(), nullable=False)
        )

    op.drop_table("tile_styles")
    # ### end Alembic commands ###
