from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a7dcbe76d7c6"
down_revision: str | None = "544913320a42"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "activity_line_color",
                sa.String(),
                server_default="#e41a1c",
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("config_ui", schema=None) as batch_op:
        batch_op.drop_column("activity_line_color")

    # ### end Alembic commands ###
