from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b134fcecaa46"
down_revision: str | None = "2c4e76738551"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "filtered_cluster_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("query_hash", sa.String(), nullable=False),
        sa.Column("zoom", sa.Integer(), nullable=False),
        sa.Column("generation", sa.Integer(), nullable=False),
        sa.Column("payload", sa.LargeBinary(), nullable=False),
        sa.Column("last_used", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "query_hash", "zoom", name="uq_filtered_cluster_cache_query_zoom"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("filtered_cluster_cache")
    # ### end Alembic commands ###
